In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

**Checking the tensorflow version**

In [2]:
tf.__version__

'2.6.4'

**Importing the data set**

In [3]:
dataset = pd.read_csv('../input/nasa-nearest-earth-objects/neo_v2.csv')
X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, -1].values

**Deleting the unwanted colums**

In [4]:
print(X)
X[:, 4] = X[:, 6]

[[1.1982708007 2.6794149658 13569.2492241812 ... 'Earth' False 16.73]
 [0.2658 0.5943468684 73588.7266634981 ... 'Earth' False 20.0]
 [0.7220295577 1.6145071727 114258.6921290512 ... 'Earth' False 17.83]
 ...
 [0.0319561887 0.0714562102 7566.8077324922 ... 'Earth' False 24.6]
 [0.0073207399 0.016369672 69199.1544835094 ... 'Earth' False 27.8]
 [0.0398616229 0.0891332986 27024.4555527296 ... 'Earth' False 24.12]]


In [5]:
X = np.delete(X, 6, axis=1)
print(X)

[[1.1982708007 2.6794149658 13569.2492241812 54839744.08284605 16.73
  False]
 [0.2658 0.5943468684 73588.7266634981 61438126.52395093 20.0 False]
 [0.7220295577 1.6145071727 114258.6921290512 49798724.94045679 17.83
  False]
 ...
 [0.0319561887 0.0714562102 7566.8077324922 28400768.1610167 24.6 False]
 [0.0073207399 0.016369672 69199.1544835094 68692060.5345607 27.8 False]
 [0.0398616229 0.0891332986 27024.4555527296 59772130.59268528 24.12
  False]]


In [6]:
X = np.delete(X, 5, axis=1)
print(X)

[[1.1982708007 2.6794149658 13569.2492241812 54839744.08284605 16.73]
 [0.2658 0.5943468684 73588.7266634981 61438126.52395093 20.0]
 [0.7220295577 1.6145071727 114258.6921290512 49798724.94045679 17.83]
 ...
 [0.0319561887 0.0714562102 7566.8077324922 28400768.1610167 24.6]
 [0.0073207399 0.016369672 69199.1544835094 68692060.5345607 27.8]
 [0.0398616229 0.0891332986 27024.4555527296 59772130.59268528 24.12]]


**Splitting the data_set** 

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Making the ANN model**

In [9]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

2022-07-19 14:44:58.600185: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [10]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

2022-07-19 14:44:58.795940: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/50
2271/2271 [==============================] - 6s 2ms/step - loss: 0.2390 - accuracy: 0.9055
Epoch 2/50
2271/2271 [==============================] - 5s 2ms/step - loss: 0.1929 - accuracy: 0.9096
Epoch 3/50
2271/2271 [==============================] - 5s 2ms/step - loss: 0.1892 - accuracy: 0.9111
Epoch 4/50
2271/2271 [==============================] - 5s 2ms/step - loss: 0.1874 - accuracy: 0.9118
Epoch 5/50
2271/2271 [==============================] - 5s 2ms/step - loss: 0.1868 - accuracy: 0.9117
Epoch 6/50
2271/2271 [==============================] - 5s 2ms/step - loss: 0.1865 - accuracy: 0.9121
Epoch 7/50
2271/2271 [==============================] - 5s 2ms/step - loss: 0.1862 - accuracy: 0.9122
Epoch 8/50
2271/2271 [==============================] - 5s 2ms/step - loss: 0.1860 - accuracy: 0.9123
Epoch 9/50
2271/2271 [==============================] - 4s 2ms/step - loss: 0.1858 - accuracy: 0.9122
Epoch 10/50
2271/2271 [==============================] - 5s 2ms/step - loss: 0.185

In [11]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[False False]
 [False  True]
 [False False]
 ...
 [False False]
 [False False]
 [False False]]


**Evaluating an accuracy_scory**

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[16322    51]
 [ 1538   257]]


0.9125385292822545